function writeToCsv(csvOutput, rawCsvOutput, rawCsvName, csvName)
    if(exist(rawCsvName, 'file') ~= 2)
        fileID = fopen(rawCsvName, 'a+');
        fprintf(fileID, '%s, %s, %s, %s, %s, %s, %s, %s', ...
            'Session Index', ...
            'Type', ...
            'Subject Code', ...
            'Date', ...
            'Protocol', ...
            'Mean', ...
            'Standard Deviation', ...
            'Standard Error');
        fclose(fileID);
    end
    % Print statistics for each subject, for each experiment to csv
    fileID = fopen(rawCsvName, 'a+');
    for i = size(rawCsvOutput,1)
        fprintf(fileID, '\n%s, %s, %s, %s, %s, %5.4f, %5.4f, %7.6f', ...
            rawCsvOutput{i,:});
    end
    fclose(fileID);  
        
    if(exist(csvName, 'file') ~= 2)
    	fileID = fopen(csvName, 'a+');
    	formatSpec = '%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s';
        fprintf(fileID, formatSpec, ...
                '', ...
                '', ...
                '', ...
                '', ...
                'T1', ...
                'T1', ...
                'T1', ...
                '', ...
                'CP', ...
                'CP', ...
                'CP', ...
                '', ...
                'CPO', ...
                'CPO', ...
                'CPO', ...
                '', ...
                'CC 9x9', ...
                'CC 9x9', ...
                'CC 9x9', ...
                '', ...
                'CC 3x3', ...
                'CC 3x3', ...
                'CC 3x3', ...
                '', ...
                'IC', ...
                'IC', ...
                'IC', ...
                '', ...
                'CP 9x9', ...
                'CP 9x9', ...
                'CP 9x9');
        fprintf(fileID, formatSpec, ...
                'Session Index', ...
                'Type', ...
                'Subject Code', ...
                'Date', ...
                'Mean', ...
                'Standard Deviation', ...
                'Standard Error', ...
                '', ...
                'Mean', ...
                'Standard Deviation', ...
                'Standard Error', ...
                '', ...
                'Mean', ...
                'Standard Deviation', ...
                'Standard Error', ...
                '', ...
                'Mean', ...
                'Standard Deviation', ...
                'Standard Error', ...
                '', ...
                'Mean', ...
                'Standard Deviation', ...
                'Standard Error', ...
                '', ...
                'Mean', ...
                'Standard Deviation', ...
                'Standard Error', ...
                '', ...
                'Mean', ...
                'Standard Deviation', ...
                'Standard Error');
        fclose(fileID);
    end
    
    formatSpec = '\n%s, %s, %s, %s, %4.3f, %5.4f, %10.9f, %s, %4.3f, %5.4f, %10.9f, %s, %4.3f, %5.4f, %10.9f, %s, %4.3f, %5.4f, %10.9f, %s, %4.3f, %5.4f, %10.9f, %s, %4.3f, %5.4f, %10.9f, %s, %4.3f, %5.4f, %10.9f';
    fileID = fopen(csvName, 'a+');
    fprintf(fileID, formatSpec, csvOutput{1,:});
    fclose(fileID);
end